development:
  clients:
    default:
      database: api_sample_development
      hosts:
        - mongodb:27017
      options:
        user: 'user'
        password: 'pass'
        auth_source: 'admin'
        read:
          mode: :primary
        max_pool_size: 5

test:
  clients:
    default:
      database: api_sample_test
      hosts:
        - mongodb:27017  # Assuming Docker configuration
      options:
        user: 'user'
        password: 'pass'
        auth_source: 'admin'
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: api_sample_production
      hosts:
        - <%= ENV['MONGO_HOST'] %>:<%= ENV['MONGO_PORT'] %>
      options:
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>
        auth_source: 'admin'
        read:
          mode: :primary
        max_pool_size: 10
        ssl: true  # Enable SSL for production
        ssl_cert: <%= ENV['MONGO_SSL_CERT'] %>
        ssl_key: <%= ENV['MONGO_SSL_KEY'] %>
        ssl_verify: true
        ssl_ca_cert: <%= ENV['MONGO_SSL_CA_CERT'] %>
